In [6]:
import numpy as np
a = np.arange(1, 9) # Массив от 1 до 8 включительно
z = np.zeros(3)
o = np.ones(7)
ar = np.arange(0, 10, 2)
r = np.linspace(0, 1, 5)
print(a, a.shape, a.dtype)

b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)
print("shape:", b.shape)
print("dtype:", b.dtype)

x = np.arange(10)
print(x)
print("x[0] =", x[0])
print("x[-1] =", x[-1])
print("x[2:7] =", x[2:7])
print("x[::2] =", x[::2])

m = np.arange(16).reshape(4, 4)
print(m)
print("Элемент [1,2]:", m[1, 2])
print("Вторая строка:", m[1, :])
print("Третий столбец:", m[:, 2])
print("Подматрица 2x2:\n", m[1:3, 1:3])

[1 2 3 4 5 6 7 8] (8,) int64
[[1 2 3]
 [4 5 6]]
shape: (2, 3)
dtype: int64
[0 1 2 3 4 5 6 7 8 9]
x[0] = 0
x[-1] = 9
x[2:7] = [2 3 4 5 6]
x[::2] = [0 2 4 6 8]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Элемент [1,2]: 6
Вторая строка: [4 5 6 7]
Третий столбец: [ 2  6 10 14]
Подматрица 2x2:
 [[ 5  6]
 [ 9 10]]
