In [1]:
import numpy as np

a = np.arange(1, 9)
z = np.zeros(3)
o = np.ones(7)
ar = np.arange(0, 10, 2)
r = np.linspace(0, 1, 5)

b = np.array([[1, 2, 3],
              [4, 5, 6]])

print("a:", a)
print("z:", z)
print("o:", o)
print("ar:", ar)
print("r:", r)
print("b:\n", b)

print("\n--- shape / dtype ---")
print("a.shape:", a.shape, "| a.dtype:", a.dtype)
print("b.shape:", b.shape, "| b.dtype:", b.dtype)
print("r.shape:", r.shape, "| r.dtype:", r.dtype)

x = np.arange(10)
print("\nМассив x:", x)
print("x[0] =", x[0])
print("x[-1] =", x[-1])
print("x[2:7] =", x[2:7])
print("x[::2] =", x[::2])

m = np.arange(16).reshape(4, 4)
print("\nМатрица m:\n", m)
print("Элемент [1, 2]:", m[1, 2])
print("Вторая строка:", m[1, :])
print("Третий столбец:", m[:, 2])
print("Подматрица 2x2:\n", m[1:3, 1:3])

print("\n--- Простые операции ---")
print("a      :", a)
print("a + 5  :", a + 5)
print("a * 2  :", a * 2)
print("a ** 2 :", a ** 2)

print("\nСложение массивов:")
print("ar:", ar)
print("ar + a[:5]:", ar + a[:5])

print("\n--- Статистики для a ---")
print("sum(a):", a.sum())
print("mean(a):", a.mean())
print("min(a):", a.min())
print("max(a):", a.max())
print("std(a):", a.std())

print("\n--- Статистики для m ---")
print("sum(m):", m.sum())
print("mean(m):", m.mean())
print("min(m):", m.min())
print("max(m):", m.max())
print("mean axis=0:", m.mean(axis=0))
print("mean axis=1:", m.mean(axis=1))

a: [1 2 3 4 5 6 7 8]
z: [0. 0. 0.]
o: [1. 1. 1. 1. 1. 1. 1.]
ar: [0 2 4 6 8]
r: [0.   0.25 0.5  0.75 1.  ]
b:
 [[1 2 3]
 [4 5 6]]

--- shape / dtype ---
a.shape: (8,) | a.dtype: int64
b.shape: (2, 3) | b.dtype: int64
r.shape: (5,) | r.dtype: float64

Массив x: [0 1 2 3 4 5 6 7 8 9]
x[0] = 0
x[-1] = 9
x[2:7] = [2 3 4 5 6]
x[::2] = [0 2 4 6 8]

Матрица m:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Элемент [1, 2]: 6
Вторая строка: [4 5 6 7]
Третий столбец: [ 2  6 10 14]
Подматрица 2x2:
 [[ 5  6]
 [ 9 10]]

--- Простые операции ---
a      : [1 2 3 4 5 6 7 8]
a + 5  : [ 6  7  8  9 10 11 12 13]
a * 2  : [ 2  4  6  8 10 12 14 16]
a ** 2 : [ 1  4  9 16 25 36 49 64]

Сложение массивов:
ar: [0 2 4 6 8]
ar + a[:5]: [ 1  4  7 10 13]

--- Статистики для a ---
sum(a): 36
mean(a): 4.5
min(a): 1
max(a): 8
std(a): 2.29128784747792

--- Статистики для m ---
sum(m): 120
mean(m): 7.5
min(m): 0
max(m): 15
mean axis=0: [6. 7. 8. 9.]
mean axis=1: [ 1.5  5.5  9.5 13.5]
